services:
  - type: web
    name: onyx-backend
    env: node
    repo: https://github.com/getmobilehq/onyxx.git
    branch: main
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 7d
      - key: JWT_REFRESH_EXPIRE
        value: 30d
      - key: CLIENT_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: onyx-frontend
    env: static
    repo: https://github.com/getmobilehq/onyxx.git
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://onyx-backend-f7vh.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true