ALTER TABLE cleanup_backup_users ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE elements ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE elements ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE fci_reports ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE field_assessments ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reference_building_costs ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE reference_building_costs ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tokens ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
CREATE INDEX idx_assessment_deficiencies_assessment_element_id ON assessment_deficiencies(assessment_element_id);
CREATE INDEX idx_assessment_elements_assessment_id ON assessment_elements(assessment_id);
CREATE INDEX idx_assessment_elements_element_id ON assessment_elements(element_id);
CREATE INDEX idx_assessments_assigned_to_user_id ON assessments(assigned_to_user_id);
CREATE INDEX idx_assessments_building_id ON assessments(building_id);
CREATE INDEX idx_assessments_created_by_user_id ON assessments(created_by_user_id);
CREATE INDEX idx_assessments_organization_id ON assessments(organization_id);
CREATE INDEX idx_buildings_created_by_user_id ON buildings(created_by_user_id);
CREATE INDEX idx_buildings_organization_id ON buildings(organization_id);
CREATE INDEX idx_fci_reports_assessment_id ON fci_reports(assessment_id);
CREATE INDEX idx_fci_reports_building_id ON fci_reports(building_id);
CREATE INDEX idx_fci_reports_created_by ON fci_reports(created_by);
CREATE INDEX idx_field_assessments_assessor_id ON field_assessments(assessor_id);
CREATE INDEX idx_field_assessments_building_id ON field_assessments(building_id);
CREATE INDEX idx_field_assessments_element_id ON field_assessments(element_id);
CREATE INDEX idx_pre_assessments_assessment_id ON pre_assessments(assessment_id);
CREATE INDEX idx_pre_assessments_building_id ON pre_assessments(building_id);
CREATE INDEX idx_pre_assessments_created_by_user_id ON pre_assessments(created_by_user_id);
CREATE INDEX idx_reports_assessment_id ON reports(assessment_id);
CREATE INDEX idx_reports_building_id ON reports(building_id);
CREATE INDEX idx_reports_created_by_user_id ON reports(created_by_user_id);
CREATE INDEX idx_tokens_created_by ON tokens(created_by);
CREATE INDEX idx_tokens_used_by ON tokens(used_by);
CREATE INDEX idx_users_invited_by ON users(invited_by);
CREATE INDEX idx_users_signup_token ON users(signup_token);