name: Security Monitoring

on:
  schedule:
    # Run security checks daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  security-audit:
    name: Daily Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    # Dependency Vulnerability Scanning
    - name: Install dependencies
      run: npm ci

    - name: Frontend security audit
      run: |
        echo "🔍 Running frontend security audit..."
        npm audit --audit-level moderate || echo "⚠️ Frontend vulnerabilities found"

    - name: Backend security audit
      run: |
        echo "🔍 Running backend security audit..."
        cd backend
        npm ci
        npm audit --audit-level moderate || echo "⚠️ Backend vulnerabilities found"

    # Code Security Scanning
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # Container Security (if using Docker)
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    # Check for exposed secrets
    - name: Run gitleaks
      uses: zricethezav/gitleaks-action@v1.6.0
      with:
        config-path: .gitleaks.toml

  dependency-update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Update frontend dependencies
      run: |
        npm update
        npm audit fix --audit-level moderate

    - name: Update backend dependencies
      run: |
        cd backend
        npm update
        npm audit fix --audit-level moderate

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies for security'
        title: 'Security: Dependency Updates'
        body: |
          Automated dependency updates for security fixes.
          
          🔍 **Changes:**
          - Updated npm packages to latest secure versions
          - Fixed security vulnerabilities where possible
          
          🤖 Generated by GitHub Actions
        branch: security/dependency-updates